### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by alice-hannah** [best-practice-and-impact/afcharts#13]
Some ideas:
* Check plot attributes using `ggplot2::build_plot()`
* https://vdiffr.r-lib.org/
* testthat snapshots

**Comment by Olivia-Box-Power** [comment]
Hi @jen-machin. Is there any update on this ticket?

**Comment by Olivia-Box-Power** [comment]
I've started adding tests using vdiffr.

**Comment by Olivia-Box-Power** [comment]
Merged into development branch
