### ISSUE TITLE
Bug when passing args to theme_af via use_afcharts

### ISSUE THREAD

**Issue by alice-hannah** [best-practice-and-impact/afcharts#30]
See issue #45 in sgplot repo: https://github.com/ScotGovAnalysis/sgplot/issues/45

This is the commit that fixed: https://github.com/ScotGovAnalysis/sgplot/commit/44137cc4d3ec76dac309fcd63ea9bd19fdf052bd

**Comment by Olivia-Box-Power** [comment]
Thanks Alice. Branch ready for review.

**Comment by Olivia-Box-Power** [comment]
Merged into development
