### ISSUE TITLE
Running unattached causes errors

### ISSUE THREAD

**Issue by pbrohan** [best-practice-and-impact/afcharts#32]
Just running `afcharts::use_afcharts()` without running `library(afcharts)` first gives 

``` 
Error in afcharts::use_afcharts() : object 'af_colour_values' not found
```

as the internal data isn't addressed using the namespace. 

It's an easy fix, I'll put in a PR.

**Comment by Olivia-Box-Power** [comment]
Thank you. This issue has already been fixed for the next version of afcharts.
