### ISSUE TITLE
`af_colour_palettes` as global variable

### ISSUE THREAD

**Issue by pbbgss** [best-practice-and-impact/afcharts#36]
Looks like a really useful package - thanks for putting it together!

I think the objects `af_colour_pallets` and `af_colour_vallues` being [set as global variables](https://github.com/best-practice-and-impact/afcharts/blob/29b0a4c670f5b617893ca7ececcc2b67628a6bbf/R/afcharts-package.R#L9) is causing issues if users don't want to use `library()` calls. The function `afcharts::scale_colour_discrete_af()` will return an error in the example below.

I think removing the `globalVariables()` line and using `package::object` syntax i.e. `afcharts::af_colour_palettes` whenever you reference it internally will fix this issue. 

(I'm not sure what the best practice for referencing exported data from within its package is - another option might be to have an [internal](https://usethis.r-lib.org/reference/use_data.html#arg-internal) version of the data as well as the exported version (or instead if users don't need easy access to these data). I would probably go with making the data internal and then give an exported function `return_colour_palettes()` (or similar) that users could use if they wanted to know the specific values.

Example (using CRAN install of 0.4.0)

```R
# Without a `library()` call the following code gives an error
ggplot2::economics |>
  ggplot2::ggplot(ggplot2::aes(x = date, y = pop)) +
  ggplot2::geom_line() +
  afcharts::theme_af(legend = "bottom") +
  afcharts::scale_colour_discrete_af()

# Error in af_palette(palette, reverse, palette_type = palette_type) : 
#   object 'af_colour_palettes' not found
```

**Comment by Olivia-Box-Power** [comment]
Thank you. This issue has already been fixed for the next version of the package using the package::object syntax.
