### ISSUE TITLE
Auto format large numbers on axes

### ISSUE THREAD

**Issue by nc011** [best-practice-and-impact/afcharts#41]
[Guidance](https://analysisfunction.civilservice.gov.uk/policy-store/data-visualisation-charts/#:~:text=2.-,Use%20commas%20to%20separate%20thousands,-When%20you%20have) is to use comma separated thousands on axis labels.  

Suggest making this default in the code, e.g.,

```R
plt <- plt + scale_y_continuous(labels=function(x) format(x, big.mark = ",", scientific = FALSE))
```

**Comment by Olivia-Box-Power** [comment]
Hi @nc011 

Thanks for your post. I think the scales::label_comma function may do what you're looking for.

I don't think it's possible for a package to overwrite the default y axis scale in the same way that it is possible for us to overwrite the default colour/fill scales, so I don't think we can add this in to afcharts. There may also be instances when people put other types of data on the y axis (e.g. currency, dates), which may require different formatting.

``` r
library(gapminder)
#> Warning: package 'gapminder' was built under R version 4.4.2
library(ggplot2)
#> Warning: package 'ggplot2' was built under R version 4.4.2
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.4.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(afcharts)
#> Warning: package 'afcharts' was built under R version 4.4.2

pop_bar_data <- gapminder |> 
  filter(year == 2007 & continent == "Americas") |>
  slice_max(order_by = pop, n = 5)

ggplot(pop_bar_data, aes(x = reorder(country, -pop), y = pop)) +
  geom_col(fill = af_colour_values["dark-blue"]) +
  theme_af() +
  scale_y_continuous(
    expand = c(0, 0),
    limits = c(0, 450E6),
    labels = scales::label_comma()
  )
```

![](https://i.imgur.com/J9sRBPI.png)

<sup>Created on 2024-12-16 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
